In [55]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)


cpu


In [43]:
%%time
start_time = time.time()
#martix operation here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00007176
CPU times: user 448 µs, sys: 186 µs, total: 634 µs
Wall time: 1.1 ms


In [22]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time

print(f"{elapsed_time:.8f}")


1.07568002
0.36298680


In [30]:
#torch.stack, torch.multinomial, torch.trill, torch.trio, input.T / input.transpose, nn.Linear, torch.cat, F.softmax(show all examples of functions/methods with pytorch docs)

#Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or .9 => 1. each probability points to the index of probability in the tensor
# Draw 5 samples from the mutlinomial distribution
samples = torch.multinomial(probabilities,  num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 0, 1, 1, 1, 1, 1, 1, 1])


In [27]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [29]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [32]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [33]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [34]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [44]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

#stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [51]:
import torch.nn as nn

sample = torch.tensor([10, 10, 10], dtype=torch.float32)
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 2.3734,  2.2077, -3.7464], grad_fn=<SqueezeBackward4>)


In [52]:
import torch.nn.functional as F

#create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

#apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [58]:
#Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

#Apply the embedding Layer
embedded_output = embedding(input_indices)

#The output will be a tensor of shape (4, 100) where 4 is the number
# and 100 is the dimensionality of the embedded vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[-1.8129e+00,  1.0794e+00, -5.6173e-01,  6.3130e-01, -5.0479e-01,
          7.2357e-01],
        [ 1.4875e-01, -2.1120e-04, -6.0209e-01, -1.1206e+00,  5.2090e-01,
         -1.0031e+00],
        [-3.0077e-01, -1.3441e+00,  2.7441e-01, -1.1563e+00, -7.2561e-01,
         -7.8925e-01],
        [ 1.8935e+00,  4.8543e-01,  2.8403e+00,  1.2074e+00, -3.2975e-02,
         -6.5246e-01]], grad_fn=<EmbeddingBackward0>)


In [60]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a @ b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [62]:
int_64 = torch.randint(1, (3,2), dtype=torch.float32)
#type int64
float_32 = torch.rand(2,3, dtype=torch.float32)
#type float32
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [67]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x,y,z)
print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
2 3 5
torch.Size([2, 3, 5])


In [72]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B * T, C)
print(output)
#print(input)
print(output[:, -1])

tensor([[0.1030, 0.1522, 0.5921, 0.7817, 0.3155, 0.3279, 0.4950, 0.1224, 0.3586,
         0.1466],
        [0.6682, 0.6144, 0.0406, 0.8635, 0.4083, 0.0489, 0.4022, 0.4400, 0.2494,
         0.0971],
        [0.1856, 0.1086, 0.4997, 0.5723, 0.3347, 0.1241, 0.1912, 0.5130, 0.7606,
         0.5680],
        [0.7089, 0.1490, 0.9530, 0.3803, 0.1958, 0.6961, 0.5551, 0.1373, 0.2044,
         0.9353],
        [0.4740, 0.9403, 0.9242, 0.1455, 0.1414, 0.1328, 0.7652, 0.0051, 0.9633,
         0.7914],
        [0.6088, 0.1917, 0.2879, 0.6619, 0.3339, 0.0172, 0.8299, 0.5758, 0.7545,
         0.6856],
        [0.1552, 0.2469, 0.5389, 0.1168, 0.8078, 0.6597, 0.7885, 0.7094, 0.3136,
         0.6165],
        [0.7673, 0.1169, 0.6254, 0.6852, 0.8442, 0.2309, 0.4499, 0.9111, 0.8617,
         0.5111],
        [0.5276, 0.0785, 0.3995, 0.9535, 0.6486, 0.6607, 0.3877, 0.5067, 0.6563,
         0.1624],
        [0.1125, 0.0314, 0.8694, 0.9613, 0.2051, 0.8040, 0.2771, 0.6011, 0.6294,
         0.8237],
        [0

In [78]:
x = torch.tensor([-0.05], dtype=torch.float32)
y = torch.tanh(x)
print(y)


tensor([-0.0500])
